/**
 * Turns a captured layout into a script for the Figma Plugin API.
 *
 * The output is plain JavaScript with top-level await. Run it from the bundled
 * dom2figma Figma plugin, or paste it into any plugin that evaluates code with
 * `figma` in scope.
 */

const INTER = { 300: 'Light', 400: 'Regular', 500: 'Medium', 600: 'Semi Bold', 700: 'Bold', 800: 'Extra Bold', 900: 'Black' }
const NO_SPACE = { 300: 'Light', 400: 'Regular', 500: 'Medium', 600: 'SemiBold', 700: 'Bold', 800: 'ExtraBold', 900: 'Black' }

/**
 * Map a CSS font-family + weight onto a font Figma actually has.
 * Override it when your design system uses different families.
 */
export function defaultFontMap (family, weight, { fallback = 'Inter', families = [] } = {}) {
  const f = (family || '').toLowerCase()
  const w = nearestWeight(weight)
  for (const cand of families) {
    if (f.includes(cand.match.toLowerCase())) {
      return { family: cand.family, style: (cand.noSpace ? NO_SPACE : INTER)[w] || 'Regular' }
    }
  }
  if (f.includes('mono') || f.includes('code') || f.includes('courier')) {
    return { family: 'Roboto Mono', style: NO_SPACE[w] || 'Regular' }
  }
  return { family: fallback, style: INTER[w] || 'Regular' }
}

function nearestWeight (fw) {
  const w = Number.parseInt(fw, 10)
  const n = Number.isFinite(w) ? w : 400
  return Object.keys(INTER).map(Number).reduce((a, b) => (Math.abs(b - n) < Math.abs(a - n) ? b : a))
}

const SHADOW = /rgba?\(([^)]+)\)\s*(-?[\d.]+)px\s*(-?[\d.]+)px\s*(-?[\d.]+)px(?:\s*(-?[\d.]+)px)?/
function parseShadow (s) {
  const m = SHADOW.exec(s || '')
  if (!m) return null
  const p = m[1].split(',').map(Number)
  const a = p.length > 3 ? p[3] : 1
  if (a < 0.02) return null
  return [
    round(p[0] / 255), round(p[1] / 255), round(p[2] / 255), round(a),
    Number(m[2]), Number(m[3]), Number(m[4]), m[5] ? Number(m[5]) : 0
  ]
}
const round = (n) => Math.round(n * 1000) / 1000

const ALIGN = { center: 'CENTER', right: 'RIGHT', end: 'RIGHT', justify: 'JUSTIFIED' }

/**
 * @param {object} layout   result of capture()
 * @param {object} [opts]
 * @param {string} [opts.name]      frame name in Figma
 * @param {string} [opts.page]      target Figma page name (created if missing)
 * @param {number} [opts.x]         frame position on the canvas
 * @param {number} [opts.y]
 * @param {Function} [opts.fontMap] (family, weight) => { family, style }
 */
export function toPayload (layout, opts = {}) {
  const {
    name = layout.url || 'Captured page',
    page = 'dom2figma', x = 0, y = 0,
    fontMap = (fam, w) => defaultFontMap(fam, w)
  } = opts

  const fonts = []
  const fontIndex = new Map()
  const fid = (fam, w) => {
    const f = fontMap(fam, w)
    const key = `${f.family}|${f.style}`
    if (!fontIndex.has(key)) { fontIndex.set(key, fonts.length); fonts.push([f.family, f.style]) }
    return fontIndex.get(key)
  }

  const nodes = layout.nodes.map((n) => {
    const o = { x: n.x, y: n.y, w: n.w, h: n.h }
    if (n.bg) o.bg = n.bg
    if (n.bc) { o.bc = n.bc; o.bw = n.bw ?? 1 }
    if (n.r) o.r = n.r
    if (n.img) o.img = n.img
    const sh = parseShadow(n.sh)
    if (sh) o.e = sh
    if (n.s) {
      o.s = n.s
      o.fs = n.fs ?? 14
      o.lh = n.lh || round((n.fs ?? 14) * 1.4)
      o.f = fid(n.ff, n.fw)
      if (n.fc) o.fc = n.fc
      const a = ALIGN[(n.ta || '').toLowerCase()]
      if (a) o.ta = a
      if (n.ul) o.ul = 1
      if (n.ls) o.ls = n.ls
      o.tx = n.tx ?? n.x
      o.ty = n.ty ?? n.y
      o.tw = Math.max(1, n.tw ?? n.w)
      // Single-line runs get an auto width so Figma's slightly different metrics
      // cannot introduce a line break the browser never had.
      if ((n.th ?? n.h) <= o.lh * 1.6) o.one = 1
    }
    return o
  })

  const bg = layout.nodes.slice(0, 3).find((n) => n.bg)?.bg ?? [1, 1, 1, 1]
  return { w: layout.w, h: layout.h, bg, fonts, nodes, name, page, x, y }
}

/**
 * Emit a standalone script for any Figma plugin that evaluates code with
 * `figma` in scope (Scripter, for instance). The bundled plugin takes the
 * payload from toPayload() instead and skips code evaluation entirely.
 */
export function toFigmaScript (layout, opts = {}) {
  const p = toPayload(layout, opts)
  const data = { w: p.w, h: p.h, bg: p.bg, fonts: p.fonts, nodes: p.nodes }
  return [
    BUILDER_PROLOGUE,
    'const D = ' + JSON.stringify(data),
    'const NAME = ' + JSON.stringify(p.name),
    'const PAGE = ' + JSON.stringify(p.page),
    'const OX = ' + p.x + ', OY = ' + p.y,
    BUILDER_BODY
  ].join('\n')
}

const BUILDER_PROLOGUE = '// Generated by dom2figma. Run inside a Figma plugin with `figma` in scope.'

export const BUILDER_BODY = `
let target = figma.root.children.find(p => p.name === PAGE)
if (!target) { target = figma.createPage(); target.name = PAGE }
await figma.setCurrentPageAsync(target)

const F = []
for (const f of D.fonts) {
  const fn = { family: f[0], style: f[1] }
  try { await figma.loadFontAsync(fn); F.push(fn) }
  catch (e) {
    const alt = { family: 'Inter', style: 'Regular' }
    await figma.loadFontAsync(alt); F.push(alt)
  }
}

const previous = target.children.find(c => c.name === NAME)
if (previous) previous.remove()

const root = figma.createFrame()
root.name = NAME
target.appendChild(root)
root.x = OX; root.y = OY
root.resize(D.w, D.h)
root.clipsContent = true
root.fills = [{ type: 'SOLID', color: { r: D.bg[0], g: D.bg[1], b: D.bg[2] } }]

const fill = a => [{ type: 'SOLID', color: { r: a[0], g: a[1], b: a[2] }, opacity: a[3] }]

let boxes = 0, texts = 0, images = 0, imageErrors = 0
for (const n of D.nodes) {
  const w = Math.max(1, n.w), h = Math.max(1, n.h)
  if (n.bg || n.bc || n.img || n.e) {
    const r = figma.createRectangle()
    root.appendChild(r)
    r.x = n.x; r.y = n.y
    r.resize(w, h)
    r.name = n.img ? 'image' : 'box'
    r.fills = n.bg ? fill(n.bg) : []
    if (n.bc) { r.strokes = fill(n.bc); r.strokeWeight = Math.max(0.5, n.bw); r.strokeAlign = 'INSIDE' }
    if (n.r) {
      r.topLeftRadius = n.r[0]; r.topRightRadius = n.r[1]
      r.bottomRightRadius = n.r[2]; r.bottomLeftRadius = n.r[3]
    }
    if (n.e) {
      r.effects = [{
        type: 'DROP_SHADOW', color: { r: n.e[0], g: n.e[1], b: n.e[2], a: n.e[3] },
        offset: { x: n.e[4], y: n.e[5] }, radius: n.e[6], spread: n.e[7],
        visible: true, blendMode: 'NORMAL'
      }]
    }
    if (n.img) {
      try {
        const im = await figma.createImageAsync(n.img)
        r.fills = [{ type: 'IMAGE', scaleMode: 'FILL', imageHash: im.hash }]
        images++
      } catch (e) { imageErrors++ }
    }
    boxes++
  }
  if (n.s) {
    const t = figma.createText()
    root.appendChild(t)
    t.fontName = F[n.f]
    t.fontSize = Math.max(1, n.fs)
    t.lineHeight = { unit: 'PIXELS', value: Math.max(1, n.lh) }
    t.characters = n.s
    if (n.fc) t.fills = fill(n.fc)
    if (n.ul) t.textDecoration = 'UNDERLINE'
    if (n.ls) t.letterSpacing = { unit: 'PIXELS', value: n.ls }
    if (n.ta) t.textAlignHorizontal = n.ta
    if (n.one) { t.textAutoResize = 'WIDTH_AND_HEIGHT' }
    else { t.textAutoResize = 'HEIGHT'; t.resize(Math.max(1, n.tw) + 2, t.height) }
    t.x = n.tx; t.y = n.ty
    t.name = n.s.slice(0, 40)
    texts++
  }
}

const summary = { frame: root.id, boxes, texts, images, imageErrors }
if (typeof print === 'function') print(JSON.stringify(summary))
summary
`
